service:
  name: rest-api
  namespace: default
  hostName: ""
  port: 8000
  image:
    repository: ""
    tag: ""
  autoscaling:
    minScale: 1
    maxScale: 10
    targetUtilizationPercentage: 60
    concurrency: 4
  env:
    - name: DJANGO_SETTINGS_MODULE
      value: "django_project.settings_qa"
    - name: GUNICORN_WORKERS
      value: 4
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"

celery:
  scheduler:
    name: celery-scheduler
    namespace: default
    image:
      repository: ""
      tag: ""
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: "django_project.settings_qa"
    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"
  flower:
    name: flower
    namespace: default
    hostName: ""
    port: 5555
    image:
      repository: ""
      tag: ""
    autoscaling:
      minScale: 1
      maxScale: 10
      targetUtilizationPercentage: 60
      concurrency: 1
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: "django_project.settings_qa"
    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"
  worker:
    name: celery-worker
    namespace: default
    image:
      repository: ""
      tag: ""
    autoscaling:
      minScale: 1
      maxScale: 10
      queueLengthTarget: 10
      queueName: celery
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: "django_project.settings_qa"
      - name: CELERY_BROKER_URL
        valueFrom:
          secretKeyRef:
            name: django-rest-api
            key: celery_broker_url
            optional: false
    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"
