apiVersion: batch/v1
kind: Job
metadata:
  name: collectstatic
spec:
  template:
    spec:
      containers:
        - name: collectstatic-container
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
          command: ["python", "manage.py", "collectstatic"]
          {{- with  .Values.service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.service.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          workingDir: /usr/src/app/django
      restartPolicy: Never
  backoffLimit: 1
