apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.celery.flower.name }}-deployment"
  namespace: "{{ .Values.celery.flower.namespace }}"
  labels:
    app: "{{ .Values.celery.flower.name }}-app"
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ .Values.celery.flower.name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.celery.flower.name }}-app"
    spec:
      volumes:
        - name: rest-api-logs
          hostPath:
            path: /var/logs/rest-api/
        - name: secret-volume
          secret:
            secretName: django-rest-api
      containers:
        - name: "{{ .Values.celery.flower.name }}-docker-image"
          image: "{{ .Values.celery.flower.image.repository }}:{{ .Values.celery.flower.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rest-api-logs
              mountPath: /logs/
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: {{ .Values.celery.flower.port }}
          {{- with  .Values.celery.flower.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.celery.flower.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: FLOWER_USER
              valueFrom:
                secretKeyRef:
                  name: django-rest-api
                  key: flower_user
            - name: FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-rest-api
                  key: flower_password
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.celery.flower.name }}-load-balancer"
spec:
  selector:
    app: "{{ .Values.celery.flower.name }}-app"
  ports:
    - port: 80
      name: http
      targetPort: {{ .Values.celery.flower.port }}
    - port: 443
      name: https
      targetPort: {{ .Values.celery.flower.port }}
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.celery.flower.name }}-scaler"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.celery.flower.name }}-deployment"
  minReplicas: {{ .Values.celery.flower.autoscaling.minScale }}
  maxReplicas: {{ .Values.celery.flower.autoscaling.maxScale }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.celery.flower.autoscaling.targetUtilizationPercentage }}