apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.celery.flower.name }}-deployment"
  namespace: "{{ .Values.celery.flower.namespace }}"
  labels:
    app: "{{ .Values.celery.flower.name }}-app"
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ .Values.celery.flower.name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.celery.flower.name }}-app"
    spec:
      volumes:
        - name: celery-flower-logs
          hostPath:
            path: /var/logs/celery-flower/
        - name: secret-volume
          secret:
            secretName: django-rest-api
      containers:
        - name: "{{ .Values.celery.flower.name }}-docker-image"
          image: "{{ .Values.celery.flower.image.repository }}:{{ .Values.celery.flower.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: celery-flower-logs
              mountPath: /logs/
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: {{ .Values.celery.flower.port }}
          {{- with  .Values.celery.flower.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.celery.flower.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: FLOWER_USER
              valueFrom:
                secretKeyRef:
                  name: django-rest-api
                  key: flower_user
            - name: FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-rest-api
                  key: flower_password
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.celery.flower.name }}-load-balancer"
  annotations:
    haproxy.org/pod-maxconn: "{{ .Values.celery.flower.autoscaling.concurrencyPerPod }}"
spec:
  selector:
    app: "{{ .Values.celery.flower.name }}-app"
  ports:
    - port: 80
      name: http
      targetPort: {{ .Values.celery.flower.port }}
    - port: 443
      name: https
      targetPort: {{ .Values.celery.flower.port }}
  type: ClusterIP

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 name: "{{ .Values.celery.flower.name }}-scaled-object"
spec:
 scaleTargetRef:
   kind: Deployment       
   name: "{{ .Values.celery.flower.name }}-deployment"
 pollingInterval: 20
 minReplicaCount: {{ .Values.celery.flower.autoscaling.minScale }}                 
 maxReplicaCount: {{ .Values.celery.flower.autoscaling.maxScale }}           
 advanced:                                 
   restoreToOriginalReplicaCount: false    
   horizontalPodAutoscalerConfig:          
     behavior:                             
       scaleDown:
         stabilizationWindowSeconds: 300
         policies:
         - type: Percent
           value: 25
           periodSeconds: 60
 triggers:
 - type: prometheus
   metadata:
     serverAddress: http://prometheus-server.default.svc.cluster.local
     metricName: haproxy_backend_current_queue
     query: sum(avg_over_time(haproxy_backend_current_queue{proxy="{{ .Values.celery.flower.namespace }}-{{ .Values.celery.flower.name }}-load-balancer-http"}[30s]))
     threshold: '10'