{{- range .Values.celery.worker.queues }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}-deployment"
  namespace: "{{ $.Values.celery.worker.namespace }}"
  labels:
    app: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}"
  template:
    metadata:
      labels:
        app: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}"
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: django-rest-api
        - name: celery-logs
          hostPath:
            path: /var/logs/celery-worker/
      terminationGracePeriodSeconds: 3600
      containers:
        - name: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}-docker-image"
          image: "{{ $.Values.celery.worker.image.repository }}:{{ $.Values.celery.worker.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- with  .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: django-rest-api
                  key: celery_broker_url
                  optional: false
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
            - name: celery-logs
              mountPath: /logs/
          readinessProbe:
            exec:
              command: ["python", "./django/django_project/celery_readiness.py"]
            initialDelaySeconds: 120
            periodSeconds: 60
          livenessProbe:
            exec:
              command:
                ["python", "./django/django_project/celery_worker_liveness.py"]
            initialDelaySeconds: 120
            periodSeconds: 60

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}-scaledobject"
  namespace: "{{ $.Values.celery.worker.namespace }}"
spec:
  scaleTargetRef:
    kind: Deployment
    name: "{{ $.Values.celery.worker.name }}-{{ .queueName | replace "_" "-" }}-deployment"
  pollingInterval: {{ .autoscaling.pollingInterval }}
  cooldownPeriod: {{ .autoscaling.cooldownPeriod }}
  maxReplicaCount: {{ .autoscaling.maxScale }}
  minReplicaCount: {{ .autoscaling.minScale }}
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: CELERY_BROKER_URL
        queueName: "{{ .queueName }}"
        mode: QueueLength
        value: "{{ .autoscaling.queueLengthTarget }}"
---
{{- end }}