apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.celery.scheduler.name }}-deployment"
  namespace: default
  labels:
    app: "{{ .Values.celery.scheduler.name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Values.celery.scheduler.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.celery.scheduler.name }}"
    spec:
      volumes:
        - name: celery-logs
          hostPath:
            path: /var/logs/celery-worker/
        - name: secret-volume
          secret:
            secretName: app-auth
      terminationGracePeriodSeconds: 10
      containers:
        - name: celery-scheduler-docker-image
          image: "{{ .Values.celery.scheduler.image.repository }}:{{ .Values.celery.scheduler.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- with  .Values.celery.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.celery.scheduler.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: celery-logs
              mountPath: /logs/
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          readinessProbe:
            exec:
              command: ["python", "./django/django_project/celery_readiness.py"]
            initialDelaySeconds: 120
            periodSeconds: 300