apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.service.name }}-ingress"
  annotations:
    cert-manager.io/issuer: "cloudflare-cluster-issuer"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        {{- range .Values.webapps}}
        - {{ .hostName }}
        {{- end }}
        - {{ .Values.service.hostName }}
        - {{ .Values.celery.flower.hostName }}
        - "websocket-{{ .Values.service.hostName }}"
      secretName: cloudflare-cluster-issuer
  rules:
    {{- range .Values.webapps}}
    - host: {{ .hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .name }}-webapp-load-balancer"
                port:
                  number: 80
    {{- end }}
    - host: {{ .Values.service.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.service.name }}-load-balancer"
                port:
                  number: 80
    - host: {{ .Values.celery.flower.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.celery.flower.name }}-load-balancer"
                port:
                  number: 80
    - host: "websocket-{{ .Values.service.hostName }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.service.name }}-websocket-load-balancer"
                port:
                  number: 80
