apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.service.name }}-ingress"
  annotations:
    cert-manager.io/issuer: "cloudflare-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/websocket-services: "{{ .Values.service.name }}-websocket-load-balancer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.service.hostName }}
        - {{ .Values.celery.flower.hostName }}
        - "websocket-{{ .Values.service.hostName }}"
      secretName: cloudflare-cluster-issuer
  rules:
    - host: {{ .Values.service.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.service.name }}-load-balancer"
                port:
                  number: 80
    - host: {{ .Values.celery.flower.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.celery.flower.name }}-load-balancer"
                port:
                  number: 80
    - host: "websocket-{{ .Values.service.hostName }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.service.name }}-websocket-load-balancer"
                port:
                  number: 80
