apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: django-rest-api
      containers:
        - name: django-migrate-container
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
          command: ["python", "manage.py", "migrate"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          {{- with  .Values.service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.service.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          workingDir: /usr/src/app/django
      restartPolicy: Never
  backoffLimit: 1